# Generated by Django 3.2 on 2021-05-02 01:54

import app.validade_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCreditRequest',
            fields=[
                ('proposal_number', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('credit_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[app.validade_fields.validate_credit])),
                ('status', models.CharField(default='Proposta em analise', editable=False, max_length=25)),
                ('message_status', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ticket_credit_request',
            },
        ),
    ]
