# Generated by Django 3.2 on 2021-05-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcreditrequest',
            name='message_status',
            field=models.TextField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
